### PR TITLE
with open()

### PR DESCRIPTION
**Pull request by cclauss**
There are still one or two PEP8 issues ;-)

### CODE REVIEW

**Comment by controversial** [comment]
I was actually _just_ fixing PEP8 issues. I'll push that, then I'll incorporate your changes.

I found a PEP8 linter for atom, and little yellow dots lit up everywhere (it complained about my use of tabs a lot, and the rest of my code wasn't great either.)

**Comment by controversial** [comment]
OK, I fixed PEP8 style things. I'll put in `with` statements now.

**Comment by controversial** [comment]
Incorporated changes. Thanks ;)

**Comment by cclauss** [comment]
"A Foolish Consistency is the Hobgoblin of Little Minds" -- PEP8

Great video about taking PEP8 too seriously.  https://www.youtube.com/watch?v=wf-BqAjZb8M

**Comment by controversial** [comment]
No time to watch that now, but I'll save it and watch it when I can ;)

**Comment by controversial** [comment]
I've officially imported so many things from PIL that I've exceeded the line length, and the worst part is my code uses all of them.

**Comment by cclauss** [comment]
``` python
from PIL import (Image, ImageDraw, ImageEnhance,
                    ImageFilter, ImageFont, ImageStat)
```

**Comment by controversial** [comment]
Thanks, that’s awseome. I took out ImageFilter, so I’m good now. I didn’t
know about lists of imports, though, that’s very useful.

**Pull request closed without merging**
